apiVersion: v1
kind: Secret
metadata: 
  name: walletpulse-secret
type: Opaque
stringData: 
  MONGO_URI: "mongodb+srv://erandesamadhan2003_db_user:SnynXgudfQpoBg0a@cluster0.0ctwm83.mongodb.net/"
  JWT_KEY: "secretekeywalletpulse"
